// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFileRequest(arg1, arg2) {
  return window['go']['backend']['App']['AcceptFileRequest'](arg1, arg2);
}

export function CheckIP(arg1) {
  return window['go']['backend']['App']['CheckIP'](arg1);
}

export function ChooseFile() {
  return window['go']['backend']['App']['ChooseFile']();
}

export function GetInnerIP() {
  return window['go']['backend']['App']['GetInnerIP']();
}

export function SaveFile(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SaveFile'](arg1, arg2, arg3);
}

export function SelectSaveDirectory() {
  return window['go']['backend']['App']['SelectSaveDirectory']();
}

export function SendFile(arg1, arg2) {
  return window['go']['backend']['App']['SendFile'](arg1, arg2);
}

export function SendFileMeta(arg1, arg2) {
  return window['go']['backend']['App']['SendFileMeta'](arg1, arg2);
}

export function Shutdown(arg1) {
  return window['go']['backend']['App']['Shutdown'](arg1);
}

export function StartServer() {
  return window['go']['backend']['App']['StartServer']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}
