// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {net} from '../models';
import {context} from '../models';

export function AcceptFileRequest(arg1:string,arg2:number):Promise<void>;

export function CheckIP(arg1:string):Promise<boolean>;

export function ChooseFile():Promise<string>;

export function GetInnerIP():Promise<string>;

export function SaveFile(arg1:string,arg2:number,arg3:net.Conn):Promise<void>;

export function SelectSaveDirectory():Promise<string>;

export function SendFile(arg1:string,arg2:number):Promise<void>;

export function SendFileMeta(arg1:string,arg2:string):Promise<void>;

export function Shutdown(arg1:context.Context):Promise<void>;

export function StartServer():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
